# ..gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed ..gqlgen.yml documentation.

schema:
- graphql/schema.graphql
exec:
  filename: graphql/generated.go
  package: graphql
model:
  filename: graphql/models.go
  package: graphql
models:
  User:
    fields:
      categories:
        resolver: true
      laterArticles:
        resolver: true
  Category:
    fields:
      feeds:
        resolver: true
  Feed:
    fields:
      articles:
        resolver: true
resolver:
  filename: resolver/resolver.go
  package: resolver
  type: Resolver
struct_tag: json
