language: go
sudo: false
go:
  - "1.11"
before_install:
  - go get github.com/mattn/goveralls
script:
  - go build
  - go test -v ./... -covermode=count -coverprofile=coverage.out -coverpkg="github.com/XMatrixStudio/BlogReaper/..."
  - $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci
