Violet:
  ClientID: your_violet_client_id
  ClientKey: your_violet_client_key
  ServerHost: https://oauth.xmatrix.studio/api/v2/
  LoginURL: https://oauth.xmatrix.studio/Verify/Authorize/
Server:
  Port: 30003
Database:
  IP: your_database_ip
  Port: your_database_port
  Name: your_database_name
  Username: your_username
  Password: your_password
